# Generated by Django 6.0.2 on 2026-02-13 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('voter', 'Électeur'), ('co', 'Centre de Comptage'), ('de', 'Centre de Déploiement')], default='voter', max_length=10, verbose_name='Rôle'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='VoterInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generated_password', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invité'), ('PENDING', 'En attente de validation'), ('AUTHORIZED', 'Autorisé'), ('VOTED', 'A voté'), ('REJECTED', 'Rejeté'), ('EXPIRED', 'Expiré')], default='INVITED', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('form_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='elections.election')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voter_invitations',
                'ordering': ['-invited_at'],
                'unique_together': {('email', 'election')},
            },
        ),
    ]
