# Generated by Django 6.0.2 on 2026-02-10 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('party', models.CharField(blank=True, max_length=255, verbose_name='Parti politique')),
                ('program', models.TextField(verbose_name='Programme électoral')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election', verbose_name='Élection')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['election', 'order', 'name'],
                'unique_together': {('election', 'name')},
            },
        ),
    ]
