# Generated by Django 6.0.2 on 2026-02-10 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptedBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True, verbose_name='ID Unique')),
                ('decrypted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de déchiffrement')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='candidates.candidate', verbose_name='Candidat')),
                ('decrypted_by', models.ForeignKey(limit_choices_to={'role': 'de'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decrypted_ballots', to=settings.AUTH_USER_MODEL, verbose_name='Déchiffré par')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decrypted_ballots', to='elections.election', verbose_name='Élection')),
            ],
            options={
                'verbose_name': 'Bulletin Déchiffré',
                'verbose_name_plural': 'Bulletins Déchiffrés',
                'ordering': ['-decrypted_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1_identity', models.TextField(help_text="Encrypted with CO's public key", verbose_name='Message 1 (Identité chiffrée)')),
                ('m2_ballot', models.TextField(help_text="Encrypted with DE's public key", verbose_name='Message 2 (Bulletin chiffré)')),
                ('unique_id', models.CharField(max_length=255, unique=True, verbose_name='ID Unique')),
                ('status', models.CharField(choices=[('pending_co', 'En attente CO'), ('approved_co', 'Approuvé par CO'), ('rejected_co', 'Rejeté par CO'), ('pending_de', 'En attente DE'), ('counted', 'Compté')], default='pending_co', max_length=20, verbose_name='Statut')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('co_verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification CO')),
                ('co_notes', models.TextField(blank=True, verbose_name='Notes CO')),
                ('decrypted_identity', models.JSONField(blank=True, help_text='Only contains voter info, NOT vote choice', null=True, verbose_name='Identité déchiffrée')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election', verbose_name='Élection')),
                ('verified_by_co', models.ForeignKey(blank=True, limit_choices_to={'role': 'co'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_votes', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par CO')),
                ('voter', models.ForeignKey(limit_choices_to={'role': 'voter'}, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='Électeur')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-submitted_at'],
                'unique_together': {('election', 'voter')},
            },
        ),
        migrations.CreateModel(
            name='VoteReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=64, unique=True, verbose_name='Code de reçu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='votes.vote', verbose_name='Vote')),
            ],
            options={
                'verbose_name': 'Reçu de Vote',
                'verbose_name_plural': 'Reçus de Vote',
                'ordering': ['-created_at'],
            },
        ),
    ]
