# Generated by Django 6.0.2 on 2026-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_vote_co_verified_at_vote_co_verified_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='linking_id',
            field=models.CharField(blank=True, help_text="Hash SHA-256 pour lier M1 et M2 sans révéler l'identité", max_length=64, null=True, verbose_name='Linking ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(choices=[('pending_co', 'En attente CO'), ('pending_de', 'En attente DE'), ('rejected_co', 'Rejeté par CO'), ('rejected_de', 'Rejeté par DE'), ('counted', 'Compté')], default='pending_co', max_length=20, verbose_name='Statut'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='co_notes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='co_verification_date',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='decrypted_identity',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='verified_by_co',
        ),
    ]
