# Generated by Django 6.0.2 on 2026-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_alter_vote_unique_together_vote_linking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='m2_pdf',
            field=models.FileField(blank=True, null=True, upload_to='votes/m2_pdfs/', verbose_name='PDF M2'),
        ),
    ]
