# Generated by Django 6.0.2 on 2026-02-10 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('waiting', 'En attente'), ('open', 'Ouverte'), ('closed', 'Fermée'), ('archived', 'Archivée')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('allow_multiple_votes', models.BooleanField(default=False, verbose_name='Permettre plusieurs votes')),
                ('is_public', models.BooleanField(default=True, verbose_name='Élection publique')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Élection',
                'verbose_name_plural': 'Élections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectionVoterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'assignation")),
                ('has_voted', models.BooleanField(default=False, verbose_name='A voté')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_voters', to='elections.election', verbose_name='Élection')),
                ('voter', models.ForeignKey(limit_choices_to={'role': 'voter'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_elections', to=settings.AUTH_USER_MODEL, verbose_name='Électeur')),
            ],
            options={
                'verbose_name': 'Assignation Électeur',
                'verbose_name_plural': 'Assignations Électeurs',
                'unique_together': {('election', 'voter')},
            },
        ),
    ]
