# Generated by Django 6.0.2 on 2026-02-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='co_private_key',
            field=models.TextField(blank=True, help_text='Clé privée CO (RSA)', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='co_public_key',
            field=models.TextField(blank=True, help_text='Clé publique CO (RSA)', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='de_private_key',
            field=models.TextField(blank=True, help_text='Clé privée DE (RSA)', null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='de_public_key',
            field=models.TextField(blank=True, help_text='Clé publique DE (RSA)', null=True),
        ),
    ]
